var Lang = {
	validte_required:"Can not be empty!",
		
	news_newsKeyword_len_255 : "A summary of news can not be longer than 255 characters!",
	news_newsKeyword_notEmpty : "News keyword can not be empty!",
	news_newsTitle_notEmpty : "News title can not be empty!",
	news_newsTitle_lenLess128 : "The news title cannot be longer than 32 characters!",
	news_newsTitle_special : "The news title only allows the Chinese, English, numbers, special symbols _ %@& ( part )!",
	news_newsType_notEmpty : "News type can not be empty!",
	news_newsContent_notEmpty : "News content can not be empty!",
	news_newsSourceURL_special : "news sources in URL does not meet specification!",
	news_newsSourceURL_lenLess128 : "The news sourceURL cannot be longer than 128 characters!",
	news_newsSource_lenLess128 : "he news source cannot be longer than128 characters!",
	download_downloadName_notEmpty : "Download name can not be empty!",
	download_downloadtype_notEmpty : "Download type can not be empty!",
	download_docContent_notEmpty : "Doc Content can not be empty!",
	download_upload_length_is0 : "can't upload empty file.",
	download_downloadName_lenlessthan_100 : "Download name cannot be longer than 100 characters!",
	download_downloadName_special : "Download name only allows the Chinese, English, numbers, special symbols _ %@& ( part )!",
	download_downloadDesc_lenlessthan300000 : "File description length should not exceed 300000 characters!",
	download_downloadDesc_lenless: "File description should not be empty and length should not exceed 300000 characters!",
	download_downloadFile_notEmpty : "you can't upload empty file!",
	download_downloadFile_select : "you can select doc,xls,ppt,pdf,exe,txt,rar,zip,war!",
	type_typeName_notEmpty : "type name can not be empty!",
	type_typeName_special : "Type name only allows the Chinese, English, numbers, special symbols _ %@& ( part )!",
	type_typeName_lenless32 : "Type name cannot be longer than 32 characters!",
	type_typeDesc_lenless255 : "Type description cannot be longer than 255 characters!",
	dp_audit_remake_notEmpty : "Please fill in the note",
	dp_audit_remake_lenLess200 : "Notes should not be longer than 200 characters!",
	app_price_notEmpty : "Please fill in the relevant information.",
	app_price_isnumber : "The price must be a number",
	app_price_gt0 : "Must be a number greater than 0",
	app_livel_check : "Recommended index is 1-5 positive integer",
	login_username_notEmpty : "Username can't be empty.",
	login_password_notEmpty : "Password can't be empty.",
	login_vcode_notEmpty : "Validate code can't be empty.",
	login_username_len64 : "Username cannot be longer than 64 characters.",
	login_password_len64 : "Password cannot be longer than 64 characters.",

	message : "提示信息",
	forward_Page : "请输入跳转页码！",
	file_NotDownload : "文件不存在，或者文件已删除！",
	file_khs : "【",
	file_khe : "】",
	dp_commend_remake_lenLess256 : "推荐意见不能大于256个字符",

	servaddr_name_notEmpty : "同步名称不能为空",
	servaddr_name_special : "同步名称只允许中文、英文、数字、%@&()_部分特殊符号!",
	servaddr_name_leng : "同步名称的长度不能超过64个字符",
	servaddr_url_empty : "同步地址不能为空",
	servaddr_url_special : "同步地址为wsdl地址：格式如http://localhost:8080/usp_ws/service?wsdl",
	servaddr_url_leng64 : "同步地址的长度不能超过64个字符",
	servaddr_desc_leng : "同步描述的长度不能超过512个字符",
		subjectName_notEmpty : "专题名称不许为空",
	subjectName_special : "专题名称不符合规范",
	subjectName_lenLess128 : "专题名称长度不许超过128",
	appAttachment_required : "专题图片不许为空",
	appAttachment_filter : "请选择正确格式的图片",
	appSubject_desc_required : "专题描述不许为空",
	appSubject_desc_limit : "专题描述不许超过255个字符",
	dp_type_icon_allow:"分类图标只允许jpg,gif,png格式",
	icon_allow:"分类图标只允许jpg,gif,png格式",
	certificate_name_notEmpty: "证书名称不许为空",
	certificate_name_leng: "证书名称长度不能超过128个字符",
	certificate_name_special: "证书名称只允许中文、英文、数字、%@&()_部分特殊符号！",
	certificate_file_notEmpty:"证书文件不能为空",
	certificate_signed_file_allow:"证书文件只允许cer,pem格式",
	certificate_privateKey_file_allow:"证书私钥文件只允许pk8格式",
	certificate_revoke_file_allow:"证书吊销列表文件只允许crl格式",
	certificateDesc_leng:"证书描述不许超过500个字符",
	type_typeName_unique:"分类名称已存在",

	dp_appName_require:"请填写应用名称",
	dp_appName_limit:"应用名称长度不超过100个字符",
	dp_appName_regexp:"应用名称格式不对，请重新输入",
	dp_appId_required:"请填写appId",
	dp_appId_limit:"appId不能超过255个字符",
	dp_appId_regexp:"appId格式不正确，请重新输入",
	
	dp_appTypeId_required:"请选择应用分类",
	dp_system_required:"请填写系统要求",
	dp_version_required:"请填写版本号",
	dp_appDesc_required:"请填写应用简介",
	dp_appDesc_limit:"应用简介不能超过500个字符",
	dp_price_required:"价格不能为空",
	dp_price_limit:"价格不能超过999999999",
	dp_developer_limit:"开发商不能超过255个字符",
	dp_version_limit:"版本号不能超过32个字符",
	dp_system_limit:"系统要求不能超过255个字符",
	dp_language_required:"请选择语言分类",
	appStoreClient_appName_notEmpty:"应用客户端名称不许为空",
	appStoreClient_appName_special : "应用客户端名称只能由字母、数字、汉字或及其组合!",
	appStoreClient_appName_lenlessthan_100:"应用客户端名称不能超过100个字符",
	appStoreClientPackage_notEmpty : "应用客户端安装包不能为空!",
	appStoreClientPackage_select : "只能选择apk!",
	appStoreClient_system_required:"客户端运行最小系统版本要求",
	implicitApp_appName_notEmpty:"隐式应用名称不许为空",
	implicitApp_apkPackage_notEmpty:"隐式应用包名不许为空",
	implicitApp_apkPackage_lenlessthan_100:"包名长度不能超过100个字符",
	implicitApp_appName_special : "隐式应用名称只能由字母、数字、汉字或及其组合!",
	implicitApp_appName_lenlessthan_100:"隐式应用名称不能超过100个字符",
	implicitAppPackage_notEmpty : "隐式应用安装包不能为空!",
	implicitAppPackage_select : "只能选择apk!",
	dp_sort_required:"内容不能为空",
	dp_sort_regexp:"填写的内容必须为正整数",
	dp_panelName__notEmpty:"panel name could not be empty",
	dp_panelName_lenlessthan_100:"panel name length should between zero and one hundred",
	dp_sortNum_isNum:"sort field must be number",
	dp_itemName__notEmpty:"item name could not be empty",
	dp_itemName_lenlessthan_100:"item name length should between zero and one hundred",
	dp_itemTypeValue__notEmpty:"item type value could not be empty",
	dp_handAvgScore_check:"只能是0-5的正数",
	
	only_natural_int:"请输入非负整数",
	plan_desc_limit:"方案简介不能超过255个字符",
	desc_limit:"不能超过255个字符",


};